### ISSUE TITLE
autoload missing!

### ISSUE THREAD

**Issue by trix1210** [atenadadkhah/Elite-Shop#1]
Warning: require(C:\xampp\htdocs\esm66\public/../vendor/autoload.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\esm66\public\index.php on line 34

Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs\esm66\public/../vendor/autoload.php' (include_path=

**Comment by atenadadkhah** [comment]
Hello,
Please try cleaning the cache:
`php artisan optimize`
